//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AirCompany.Module.AirCompany
{

    public partial class Airplane : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fBordName;
        public string BordName
        {
            get { return fBordName; }
            set { SetPropertyValue<string>(nameof(BordName), ref fBordName, value); }
        }
        double fMaxSpeed;
        public double MaxSpeed
        {
            get { return fMaxSpeed; }
            set { SetPropertyValue<double>(nameof(MaxSpeed), ref fMaxSpeed, value); }
        }
        int fSeatsCount;
        public int SeatsCount
        {
            get { return fSeatsCount; }
            set { SetPropertyValue<int>(nameof(SeatsCount), ref fSeatsCount, value); }
        }
        Fuel fFuel;
        [Association(@"AirplaneReferencesFuel")]
        public Fuel Fuel
        {
            get { return fFuel; }
            set { SetPropertyValue<Fuel>(nameof(Fuel), ref fFuel, value); }
        }
        Airport fAirport;
        [Association(@"AirplaneReferencesAirport")]
        public Airport Airport
        {
            get { return fAirport; }
            set { SetPropertyValue<Airport>(nameof(Airport), ref fAirport, value); }
        }
        Country fManufacturer;
        [Association(@"AirplaneReferencesCountry")]
        public Country Manufacturer
        {
            get { return fManufacturer; }
            set { SetPropertyValue<Country>(nameof(Manufacturer), ref fManufacturer, value); }
        }
        [Association(@"AviatorPilots_AirplaneAirplansReferencesAirplane")]
        public XPCollection<AviatorPilots_AirplaneAirplans> AviatorPilots_AirplaneAirplanss { get { return GetCollection<AviatorPilots_AirplaneAirplans>(nameof(AviatorPilots_AirplaneAirplanss)); } }
    }

}
