//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AirCompany.Module.AirCompany
{

    public partial class AviatorPilots_AirplaneAirplans : XPBaseObject
    {
        Airplane fAirplans;
        [Indexed(@"Pilots", Name = @"iAirplansPilots_AviatorPilots_AirplaneAirplans", Unique = true)]
        [Association(@"AviatorPilots_AirplaneAirplansReferencesAirplane")]
        public Airplane Airplans
        {
            get { return fAirplans; }
            set { SetPropertyValue<Airplane>(nameof(Airplans), ref fAirplans, value); }
        }
        Aviator fPilots;
        [Association(@"AviatorPilots_AirplaneAirplansReferencesAviator")]
        public Aviator Pilots
        {
            get { return fPilots; }
            set { SetPropertyValue<Aviator>(nameof(Pilots), ref fPilots, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
