//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AirCompany.Module.AirCompany
{

    public partial class City : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        DateTime fburnDate;
        public DateTime burnDate
        {
            get { return fburnDate; }
            set { SetPropertyValue<DateTime>(nameof(burnDate), ref fburnDate, value); }
        }
        double flatitude;
        public double latitude
        {
            get { return flatitude; }
            set { SetPropertyValue<double>(nameof(latitude), ref flatitude, value); }
        }
        double flongtitude;
        public double longtitude
        {
            get { return flongtitude; }
            set { SetPropertyValue<double>(nameof(longtitude), ref flongtitude, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fPopulation;
        public int Population
        {
            get { return fPopulation; }
            set { SetPropertyValue<int>(nameof(Population), ref fPopulation, value); }
        }
        Country fCountry;
        [Association(@"CityReferencesCountry")]
        public Country Country
        {
            get { return fCountry; }
            set { SetPropertyValue<Country>(nameof(Country), ref fCountry, value); }
        }
        bool fMetro;
        public bool Metro
        {
            get { return fMetro; }
            set { SetPropertyValue<bool>(nameof(Metro), ref fMetro, value); }
        }
        [Association(@"AirportReferencesCity")]
        public XPCollection<Airport> Airports { get { return GetCollection<Airport>(nameof(Airports)); } }
    }

}
